services:
  autoheal:
    image: willfarrell/autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  db:
    labels:
      - "autoheal=true"
    healthcheck:
      # pg_isready returns 0 when server is accepting connections.
      # Using CMD-SHELL so environment variables are expanded properly.
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER -h 127.0.0.1 || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  backend:
    build: ./backend
    environment:
      DATABASE_HOST: db
    labels:
      - "autoheal=true"
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: "/api"
    labels:
      - "autoheal=true"
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  lb:
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://127.0.0.1:80/ping | grep -q 'OK' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
